version: '3.9'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: url-shortener.mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"